### ISSUE TITLE
Training with multi-step

### ISSUE THREAD

**Issue by cj-oh** [srama2512/sidekicks#2]
Hi Santhosh, 

I could train the with a single step, but I cannot train the model with multiple steps (--T 4):
 `python main.py --T 4 --training_setting 1 --epochs 1000 \
				  --save_path saved_models/sun360/ltla/  \
				  --load_model models/sun360/one-view.net`

which stops in: 

>  "misc/State.py", line 180, in rotate
>     delta = [list(self.act_to_delta[act[i]]) for i in range(act.shape[0])]

Would you please give me any suggestions regarding this?

**Comment by srama2512** [comment]
Hi Changjae,

I just ran the above command on my setup. I had an issue with loading the model, which [others](https://github.com/pytorch/examples/issues/205) are facing as well due to older version of the model files. When I simply try
```
python main.py --T 4 --training_setting 1 --epochs 1000 \ --save_path saved_models/sun360/ltla/ 
```
it runs for me without any issues. If you are facing a specific error, could you please give more details? I'll look into it. 

[FYI - I closed the issue by mistake. Feel free to open it if it still remains unresolved.]
